spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-ticket-payment
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Nurlan2006,
    hikari:
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000





